-- Consultas Avanzadas
-- Crear una lista de los diez productos más vendidos, mostrando su nombre y la cantidad total vendida.
-- Obtener los cinco clientes con el mayor número de pedidos.
-- Listar los productos junto con el total de ingresos generados por cada uno (precio por cantidad vendida).
-- Encontrar los productos que han sido vendidos en todas las categorías.
-- Listar los nombres de los clientes y los empleados que han tenido algún contacto en común por un pedido.
-- Ejercicios de Consultas Complejas con Múltiples Uniones y Subconsultas
-- Ventas Recientes por Cliente y Último Producto Comprado
-- Obtén un reporte que liste el nombre del cliente, el último producto que compró, la cantidad comprada y la fecha del pedido. Muestra solo el pedido más reciente de cada cliente.
-- Detalles de Ventas con Método de Pago Preferido
-- Muestra los detalles de ventas, método de pago y nombre del empleado que gestionó el pedido, considerando el método de pago preferido del cliente y solo los pedidos realizados en los últimos seis meses.
-- Productos con Mayor Cantidad Vendida en Cada Categoría
-- Genera un reporte que muestre el nombre de cada categoría, el producto más vendido en esa categoría y la cantidad total vendida de ese producto.
-- Pedidos con Métodos de Envío Preferidos
-- Muestra todos los pedidos junto con los métodos de envío utilizados y las fechas de entrega estimadas. Filtra para mostrar solo los pedidos que utilizaron los métodos de envío preferidos de cada cliente.
-- Proveedores con Mayor Ingreso por Categoría
-- Obtén un reporte que muestre el nombre de cada categoría de productos y el proveedor que ha generado el mayor ingreso en ventas de productos de esa categoría.
-- Clientes con Transacciones en Múltiples Países
-- Genera un reporte de clientes que han realizado transacciones en al menos dos países diferentes. Muestra el nombre del cliente, los países y el total de pedidos realizados en cada uno.
-- Pedidos de Productos sin Stock Suficiente
-- Crea una consulta que liste los pedidos en los que no se cumple la cantidad de stock requerida. Incluye el ID del pedido, el nombre del producto, la cantidad pedida y la cantidad en stock actual.
-- Ventas Agrupadas por Categoría y Tipo de Cliente
-- Genera un reporte de ventas agrupadas por categoría de producto y tipo de cliente (por ejemplo, minorista, mayorista), mostrando el total de ventas y la cantidad de productos vendidos en cada categoría para cada tipo de cliente.
-- Proveedores Alternativos para Productos Fuera de Stock
-- Muestra los productos que están fuera de stock junto con los proveedores alternativos que ofrecen productos de la misma categoría. Incluye el nombre del producto, el proveedor actual y los proveedores alternativos disponibles.
-- Clientes con Mayor Consumo por Método de Pago
-- Crea un reporte que liste los clientes que han utilizado cada método de pago, mostrando el total de gasto por cliente y método de pago. Ordena por método de pago y luego por gasto total en orden descendente.