-- 1. Reporte de Ventas por Producto
-- Genera un reporte que muestre el nombre de cada producto, la cantidad total vendida y el ingreso total generado por las ventas de cada producto, ordenado por ingreso total en orden descendente.
-- 2. Reporte de Pedidos por Cliente
-- Crea un reporte que liste el nombre de cada cliente, la cantidad total de pedidos que ha realizado, la cantidad total de productos comprados y el gasto total realizado.
-- 3. Reporte de Ventas Mensuales
-- Realiza un reporte que muestre el total de ventas (cantidad de pedidos y monto total) por cada mes y año. Ordena los datos por año y mes en orden ascendente.
-- 4. Reporte de Empleados y Ventas Realizadas
-- Genera un reporte que contenga el nombre de cada empleado, la cantidad total de pedidos que ha gestionado, y el ingreso total generado en sus ventas. Ordena por ingreso total de mayor a menor.
-- 5. Reporte de Inventario de Productos
-- Crea un reporte con el nombre del producto, la cantidad en stock, el número de pedidos pendientes, y el valor total del inventario disponible para cada producto.
-- 6. Reporte de Clientes y Países
-- Muestra un reporte con el nombre del cliente y su país, junto con la cantidad total de pedidos realizados por los clientes de cada país. Ordena por país y, dentro de cada país, por la cantidad de pedidos en orden descendente.
-- 7. Reporte de Ventas por Categoría
-- Genera un reporte que muestre el nombre de cada categoría, la cantidad total de productos vendidos en esa categoría y el ingreso total generado. Ordena por ingreso total en orden descendente.
-- 8. Reporte de Proveedores y Productos
-- Crea un reporte que liste cada proveedor junto con el nombre de los productos que ofrece, el precio de cada producto y el total de ingresos generados por cada producto.
-- 9. Reporte de Pedidos sin Stock Suficiente
-- Realiza un reporte que liste los pedidos que contienen productos para los cuales no hay suficiente stock para satisfacer la cantidad pedida. Incluye el ID del pedido, el nombre del producto, la cantidad pedida y la cantidad en stock.
-- 10. Reporte de Productos Más Vendidos
-- Muestra un reporte de los 10 productos más vendidos en términos de cantidad de unidades. Incluye el nombre del producto, la cantidad total vendida y el ingreso total generado por cada producto.
-- 11. Reporte de Clientes con Mayor Gasto
-- Genera un reporte de los 10 clientes que más han gastado en pedidos, mostrando su nombre, el total de productos comprados y el monto total gastado.
-- 12. Reporte de Rentabilidad de Categorías
-- Crea un reporte que liste el nombre de cada categoría junto con el precio promedio de sus productos, la cantidad total de productos vendidos en esa categoría, y el ingreso total generado.
-- 13. Reporte de Productos sin Ventas
-- Genera un reporte de todos los productos que no han tenido ventas. Incluye el nombre del producto, su categoría y su precio.
-- 14. Reporte de Ventas por Región
-- Realiza un reporte que muestre el total de ventas, cantidad de pedidos y monto total generado en cada región donde existen clientes.
-- 15. Reporte de Clientes Frecuentes
-- Muestra un reporte con los clientes que han realizado al menos cinco pedidos. Incluye el nombre del cliente, la cantidad de pedidos y el gasto total.